### ISSUE TITLE
API Cloud前来围观的。。

### ISSUE THREAD

**Issue by tangxiadi** [jinlong/didiShit#1]
要不要这么恶搞。。。![image](http://ctc.qzonestyle.gtimg.cn/qzone/em/e7024.gif)价值100亿美刀。。我想问问作者，“滴滴拉屎”和“didiShit”的商标注册了吗？![image](http://ctc.qzonestyle.gtimg.cn/qzone/em/e7024.gif)![image](http://ctc.qzonestyle.gtimg.cn/qzone/em/e7024.gif)

**Comment by jinlong** [comment]
哈哈哈~商标还没注册......
